### ISSUE TITLE
eln home page: simple way to update / insert view

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/www.c6h6.org#6]
Actions on the table:
- update view to latest revision
- insert view (latest revision)

The available views can be fetch using

https://www.cheminfo.org/couch/cheminfo-public/_design/customApp/_view/docs?key=%5B%22c6h6%22%2C%22admin%40cheminfo.org%22%5D

**Comment by lpatiny** [comment]
The view already emits:  meta: content.meta, need to remember how we edit it ;)

**Comment by lpatiny** [comment]
@targos Do you know if there is a way to edit the meta data from the visualizer views manager ? It is emitted from some views like:

https://www.cheminfo.org/couch/_utils/document.html?visualizer/06d3c6ed57762b356b993a0d8138ae04

**Comment by targos** [comment]
I don't know what this feature is

**Comment by lpatiny** [comment]
@stropitek We may close this ticket ?
